prometheus:
  prometheusSpec:
    scrapeInterval: 30s
    retention: 3d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  adminPassword: "ops5grafana"
  service:
    type: ClusterIP
  persistence:
    enabled: true
    storageClassName: local-path
    size: 2Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
