apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
  namespace: default
data:
  EULA: "TRUE"
  VERSION: "1.20.4"
  MEMORY: "1536M"
  MOTD: "Primcj Minecraft Server - OPS4"
  TYPE: "VANILLA"
  ONLINE_MODE: "FALSE"